### PR TITLE
Speed improvement by  * Thread

### PR DESCRIPTION
**Pull request by Nuked88**
I've implemented a way to increase speed by alot using parallelization of the non-GPU works.
I've tested a little bit and it seems to work fine.
If you set n_threads equals to 1 it will fallback to the old system

### CODE REVIEW

**Comment by Gourieff** [comment]
Hi there
I will test it this week

**Comment by Gourieff** [comment]
Hi!
So, it seems that there's almost no any benefit when I change threads number with this method
Also we get some statuses mess in the console

One thread test:

изображение

Several threads test:

изображение

**Comment by billbo100** [comment]
Haven't looked through the code, but I was curious how you attempted to paralyze this code, and if you used Python Threads or Processes, since Threads in python likely wouldn't speed the code up much due to the GIL.

**Comment by Nuked88** [comment]
Hi, yes the problem is that i've used threads and i've discovered just recently that GIL was a problem. I don't even know why i was pretty sure that the performance was improved to me...
I postponed answering this pull because I wanted to make a modification that use multiprocessing but then I ran out of time so I ended up forgetting about it. I'll see if I can maybe do something these days.(Hoping that is possible!)

**Pull request closed without merging**
